version: 2.1

jobs:
  build:
    docker:
      - image: python:2-alpine
    steps:
      - checkout
      - run:
          name: Build steps
          command: |
            python -m py_compile sources/add2vals.py sources/calc.py
  test:
    docker:
      - image: qnib/pytest
    steps:
      - checkout
      - run:
           name: Run Tests
           command: |
             py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports/results.xml

workflows:
  full_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
